### ISSUE TITLE
regression scatter plot crashes

### ISSUE THREAD

**Issue by sonjageorgievska** [DeepRank/deeprank#123]
--> Scatter Plot : ./out_001_split_channels_n_8/prediction_0000.png
Traceback (most recent call last):
  File "train_001_split-channels_regression.py", line 208, in <module>
    main()
  File "train_001_split-channels_regression.py", line 204, in main
    hdf5='epoch_data.hdf5'
  File "/nfs/home4/sgeorgie/deeprank/deeprank/learn/NeuralNet.py", line 362, in train
    save_model=save_model)
  File "/nfs/home4/sgeorgie/deeprank/deeprank/learn/NeuralNet.py", line 721, in _train
    self._plot_scatter(figname)
  File "/nfs/home4/sgeorgie/deeprank/deeprank/learn/NeuralNet.py", line 972, in _plot_scatter_reg
    ax.scatter(targ, out, c=color_plot[l], label=l)
  File "/home/sgeorgie/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "/home/sgeorgie/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 4182, in scatter
    raise ValueError("x and y must be the same size")
ValueError: x and y must be the same size

**Comment by CunliangGeng** [comment]
@sonjageorgievska I cannot reproduce the error with simple test examples. So I guess there might be problem with your input data, such as the ground truth data.

**Comment by sonjageorgievska** [comment]
I use /projects/0/deeprank/BM5/hdf5/hdf5_withGridFeature , which test data have u used and was it updated lately? The scatter plots used to work with the old data, a year ago

**Comment by CunliangGeng** [comment]
I used the unittest examples, they work well.

**Comment by sonjageorgievska** [comment]
Were the unittests updated after changing the format of the data?

**Comment by CunliangGeng** [comment]
The unittest generates everything from the raw pdb and pssm data.
