### ISSUE TITLE
def get_feature_value() in FullPSSM.py fails on pdb files with missing CB atoms 

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/deeprank#139]
Error when running `DataGenerator()` on a pdb file with missing CB atoms. 
Code: `/projects/0/deeprank/BM5/test/hdf5_generate.py`
Error message: 
> ERROR: ('B', 47, 'THR')
> Traceback (most recent call last):
>   File "/nfs/home6/lixue1/deeprank/deeprank/generate/DataGenerator.py", line 1370, in _compute_features
>     feat_module.__compute_feature__(pdb_data, featgrp, featgrp_raw)
>   File "/nfs/home6/lixue1/deeprank/deeprank/features/PSSM_IC.py", line 22, in __compute_feature__
>     func(pdb_data, featgrp, featgrp_raw, out_type='pssmic')
>   File "/nfs/home6/lixue1/deeprank/deeprank/features/FullPSSM.py", line 262, in __compute_feature__
>     pssm.get_feature_value()
>   File "/nfs/home6/lixue1/deeprank/deeprank/features/FullPSSM.py", line 226, in get_feature_value
>     key = tuple([chain] + xyz_dict[res])
> KeyError: ('B', 47, 'THR')
> /home/lixue1/tools/pdb2sql/pdb2sql/pdb2sqlcore.py:466: UserWarning: SQL query get an empty
>   warnings.warn('SQL query get an empty')
> ERROR: list index out of range
> Traceback (most recent call last):
>   File "/nfs/home6/lixue1/deeprank/deeprank/generate/DataGenerator.py", line 1370, in _compute_features
>     feat_module.__compute_feature__(pdb_data, featgrp, featgrp_raw)
>   File "/nfs/home6/lixue1/deeprank/deeprank/features/BSA.py", line 152, in __compute_feature__
>     bsa.get_contact_residue_sasa()
>   File "/nfs/home6/lixue1/deeprank/deeprank/features/BSA.py", line 124, in get_contact_residue_sasa
>     'x,y,z', resSeq=res[1], chainID=res[0], name=atcenter)[0]
> IndexError: list index out of range
> ERROR: list index out of range
> Traceback (most recent call last):
>   File "/nfs/home6/lixue1/deeprank/deeprank/generate/DataGenerator.py", line 1370, in _compute_features
>     feat_module.__compute_feature__(pdb_data, featgrp, featgrp_raw)
>   File "/nfs/home6/lixue1/deeprank/deeprank/features/ResidueDensity.py", line 175, in __compute_feature__
>     resdens.extract_features()
>   File "/nfs/home6/lixue1/deeprank/deeprank/features/ResidueDensity.py", line 133, in extract_features
>     'x,y,z', resSeq=key[1], chainID=key[0], name=atcenter)[0]
> IndexError: list index out of range

It is caused by `get_feature_value()`, which read xyz for the CB atom as the anchor position for a residue. However, ('B', 47, 'THR') in the pdb file is missing CB atoms. ('B', 47, 'THR') has pssm values.

I have no good idea how to solve this issue. Shall we set `get_feature_value()` to read CA atoms instead of CB?

Why do we use CB instead of CA?

**Comment by NicoRenaud** [comment]
at the times we thought CB was the best option .... don't remember why though. We already default to ca for GLY. So we could simply default to CA for THR as well ...

**Comment by LilySnow** [comment]
I think I used CB to indicate the side chain of amino acid, as we focus more on side-chain interactions than backbone interactions (CA atoms). 

I thought about it. We can assume that deeprank only takes as input refined pdb files (i.e., all missing atoms are added, histidine protonation states are corrected, and clashes are removed/improved). Therefore, this is not a bug of deeprank. Could we make deeprank to report a warning/error message saying that "XXX residue is missing atoms, hence not processed by deeprank".

I will get missing atoms for this pdb file.

**Comment by NicoRenaud** [comment]
sounds good ! I'll fix that today :)

**Comment by NicoRenaud** [comment]
or we could default to the center of the residue and print a warning. So that you don't loose the residue but you only offset the center.

**Comment by NicoRenaud** [comment]
The issue is more difficult for the pssm though ...

**Comment by NicoRenaud** [comment]
do you have the pdb/pssm that create the issue ?

**Comment by LilySnow** [comment]
Data and code are under: `/projects/0/deeprank/BM5/issue139`

Using the center of the residue is a good idea. Not sure how difficult it is from your side?
