### ISSUE TITLE
mapped_features doesn't exist

### ISSUE THREAD

**Issue by sonjageorgievska** [DeepRank/deeprank#151]
**Describe the bug**
The training process crashes 

(please see the output on slack development channel)

: epoch 000 / 002 ---------------------------------------------

	=> train the model

Traceback (most recent call last):
  File "train_001_smallNN_Kfold_balance_nofilt_align-2806.py", line 208, in <module>
    main()
  File "train_001_smallNN_Kfold_balance_nofilt_align-2806.py", line 204, in main
    hdf5='epoch_data.hdf5'
  File "/nfs/home4/sgeorgie/deeprank/deeprank/learn/NeuralNet.py", line 360, in train
    save_model=save_model)
  File "/nfs/home4/sgeorgie/deeprank/deeprank/learn/NeuralNet.py", line 655, in _train
    train_loader, train_model=True)
  File "/nfs/home4/sgeorgie/deeprank/deeprank/learn/NeuralNet.py", line 780, in _epoch
    for d in data_loader:
  File "/home/sgeorgie/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/sgeorgie/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 606, in _process_next_batch
    raise Exception("KeyError:" + batch.exc_msg)
Exception: KeyError:Traceback (most recent call last):
  File "/home/sgeorgie/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/sgeorgie/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/nfs/home4/sgeorgie/deeprank/deeprank/learn/DataSet.py", line 326, in __getitem__
    feature, target = self.load_one_molecule(fname, mol)
  File "/nfs/home4/sgeorgie/deeprank/deeprank/learn/DataSet.py", line 1086, in load_one_molecule
    '\n\t'.join(list(mol_data['mapped_features'].keys()))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/sgeorgie/anaconda3/lib/python3.7/site-packages/h5py/_hl/group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'mapped_features' doesn't exist)"

srun: error: gcn35: task 0: Exited with exit code 1
srun: Terminating job step 7919726.0

**Comment by NicoRenaud** [comment]
well in all the tests we've run we do have mapped_features in the hdf5. So I'm not sure if that's a bug or an issue with the initial data ... Plus the dataset are checked for integrity and there we should check if mapped_features exists in the hdf5 ...

**Comment by sonjageorgievska** [comment]
Had a private chat with Li, she will work on it this evening ;)

**Comment by NicoRenaud** [comment]
I've pushed a new branch `issue151` that should print which molecule causes issues

**Comment by LilySnow** [comment]
I did not see this branch. Can you push it?

**Comment by NicoRenaud** [comment]
Hi Li, maybe you found the branch already but here it is : https://github.com/DeepRank/deeprank/tree/issue151

**Comment by LilySnow** [comment]
Hi Nico @NicoRenaud , I identified the failed models. They are caused by the alignment step. I created an issue 153.

**Comment by LilySnow** [comment]
issue 153 is closed thus issue151.
