### ISSUE TITLE
Missing grid_info and grid_info explanation in docs/tutorial_deeplearning.rst

### ISSUE THREAD

**Issue by DarioMarzella** [DeepRank/deeprank#185]
**Describe the bug**
In docs/tutorial_deeplearning.rst, line 28, where generating the 'data_set', grid_info is not specified.

**Actual Results or Error Info**
`Traceback (most recent call last):
  File "dl_try.py", line 51, in <module>
    dict_filter={'IRMSD':'<4. or >10.'})
  File "/home/dariomarzella/deeprank/deeprank/learn/DataSet.py", line 202, in __init__
    self.process_dataset()
  File "/home/dariomarzella/deeprank/deeprank/learn/DataSet.py", line 277, in process_dataset
    self.get_grid_shape()
  File "/home/dariomarzella/deeprank/deeprank/learn/DataSet.py", line 813, in get_grid_shape
    f'Impossible to determine sparse grid shape.\n'
ValueError: Impossible to determine sparse grid shape.
If you are not loading a pretrained model,  specify grid_shape or grid_info`

**Additional Context**
I have added the grid_info to the code block as it is in "test/test_learn.py" line 45 in commit #0ce8fd8 to branch doc_DM, but we may need a proper explanation of this feature in the tutorial.

**Comment by demainchen** [comment]
mee too! i also trap  myself in this problem and no idea to resolve this problem so far

**Comment by DarioMarzella** [comment]
> mee too! i also trap myself in this problem and no idea to resolve this problem so far

Hello demainchen, thanks for posting here your issue!
Could I ask you exactly where did you have this problem, so that I can reproduce it exactly? While running the tutorial present in the documentation (https://deeprank.readthedocs.io/en/latest/tutorial3_learning.html ) or while running a different script you made?

In the meantime, you can check the documentation for the [DataSet class](https://deeprank.readthedocs.io/en/latest/deeprank.learn.html#module-deeprank.learn.DataSet). There you can find a short explanation of what ```grid_info``` and ```grid_shape``` are.
I also just noticed there is a typo in there, I will fix it asap.

**Comment by demainchen** [comment]
hello! Thank you for your reply so quickly, I would be appreciated if u
could solve my problems.
I run this code by Google Colab, and the problem occurs while I use the
official tutorial document.
I traped in this error when I look up the "learning part" from the document(
https://deeprank.readthedocs.io/en/latest/tutorial3_learning.html#creating-training-validation-test-datasets).
The error code and the total ipynb-file I will show you by attachment.
Since I am not a native English speaker, sorry for my poor English.
Thank u again!

Dario Marzella ***@***.***> 于2021年6月17日周四 下午10:55写道：

**Comment by DarioMarzella** [comment]
Hello, it's a pleasure to help!
Unfortunately, I cannot see your attachment, could you please double check you added it to your message, or re-attach it?
I think the issue can be solved by simply giving the correct arguments to the grid_info, but I will be able to tell you once I see the code.

**Comment by demainchen** [comment]
[image: error_code.png]
[image: error_informationn.png]thanks for your resolve my problem with
patient! Can u see the picture this time?

>

**Comment by DarioMarzella** [comment]
Don't worry, it's a pleasure :)
No, not really... can you just attach the google colab file?

**Comment by demainchen** [comment]
I am very sorry for don't reply in time!
this is the Link
<https://colab.research.google.com/drive/1HUia1liS1pd4EZtDYC3i5kAgYNgg-wFQ?usp=sharing>
(
https://colab.research.google.com/drive/1HUia1liS1pd4EZtDYC3i5kAgYNgg-wFQ?usp=sharing
)
and the ipynb-file is attached

Dario Marzella ***@***.***> 于2021年6月18日周五 下午7:57写道：

**Comment by DarioMarzella** [comment]
Do not worry about the reply time, we are all busy and it can always take some time to reply.

Although I am not sure why the ```grid_shape=[30,30,30]``` is not working, I think you can solve it with grid_info.
Previously in your code, you defined the dictionary ```grid_info``` with number of points, resolution and atom type.
You should be able to use that same dictionary to build your dataset, so instead of ```grid_shape=[30,30,30]```, use ```grid_info=grid_info```.
I just modified your google colab notebook, please run it and let me know if the error is solved or not :)
