### ISSUE TITLE
When two proteins are far from each other, got error msg from ResidueDensity.py

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/deeprank#56]
Error message:

> Create database          :   0%|                | 7/25301 [00:09<9:34:43,  1.36s/it, mol=2I25_ranair-itw_387w.pdb]Error during the feature calculation of /dev/shm/2I25/2I25/2I25_ranair-itw_387w.pdb
> Traceback (most recent call last):
>   File "/nfs/home6/lixue1/deeprank/deeprank/generate/DataGenerator.py", line 282, in create_database
>     molgrp['features_raw'] )
>   File "/nfs/home6/lixue1/deeprank/deeprank/generate/DataGenerator.py", line 1103, in _compute_features
>     feat_module.__compute_feature__(pdb_data,featgrp,featgrp_raw)
>   File "/nfs/home6/lixue1/deeprank/deeprank/features/ResidueDensity.py", line 160, in __compute_feature__
>     resdens.export_data_hdf5(featgrp_raw)
>   File "/nfs/home6/lixue1/deeprank/deeprank/features/FeatureClass.py", line 64, in export_data_hdf5
>     ds = np.array(ds).astype('|S'+str(len(ds[0])))
> IndexError: list index out of range

Such pdb files should be properly reported back to the user.

**Comment by LilySnow** [comment]
I just add a pull request fro the `issue56_residueDensityBug` branch.

**Comment by LilySnow** [comment]
Here are some models for reproduce this bug:
2I25/2I25_ranair-itw_237w.pdb
2I25/2I25_ranair-it1_155.pdb
2I25/2I25_ranair-it1_387.pdb
2I25/2I25_ranair-itw_387w.pdb
2I25/2I25_cm-it0_136.pdb
2I25/2I25_ranair-it1_155.pdb
2I25/2I25_ranair-it0_2784.pdb
2I25/2I25_ranair-itw_237w.pdb
2I25/2I25_cm-it0_3183.pdb
2I25/2I25_ranair-itw_387w.pdb
2I25/2I25_cm-it0_2624.pdb
2I25/2I25_ranair-it1_387.pdb

**Comment by LilySnow** [comment]
Now the code will generate a warning message:
> WARNING: Failed to calculate ResidueDensity. This might be caused by a very small interface.
> Error during the feature calculation of /dev/shm/2I25/2I25/2I25_ranair-itw_237w.pdb
