### ISSUE TITLE
add_feature() bug when decoy name contains "_r"

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/deeprank#64]
`add_feature()` in `DataGenerator.py` breaks if decoy name contains "_r", e.g., 1AK4_ranair-it0_5257.pdb, because it mistakenly thought this is an augmented conformation. 

Error message:

> ======================================================================
> ERROR: test_4_add_feature (__main__.TestGenerateData)
> Add a feature to the database.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "test_generate.py", line 107, in test_4_add_feature
>     database.add_feature(prog_bar=True)
>   File "/home/lixue/deeprank/deeprank/deeprank/generate/DataGenerator.py", line 437, in add_feature
>     axis = aug_molgrp.attrs['axis']
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "/home/lixue/softwares/anaconda3/lib/python3.6/site-packages/h5py/_hl/attrs.py", line 60, in __getitem__
>     attr = h5a.open(self._id, self._e(name))
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5a.pyx", line 77, in h5py.h5a.open
> KeyError: "Can't open attribute (can't locate attribute: 'axis')"
> 
> ----------------------------------------------------------------------

**Comment by LilySnow** [comment]
Changed to:
```
fnames_original = list( filter(lambda x: not re.search('_r\d+$',x), fnames) )
 fnames_augmented = list( filter(lambda x:  re.search('_r\d+$',x), fnames) )
....

mol_name = re.split('_r\d+', molgrp.name)[0]
```

**Comment by LilySnow** [comment]
Also, replaced `1AK4/decoy` and `1AK4/pssm_new` under `test`. The original pdb files and pssm do not match.

**Comment by LilySnow** [comment]
merge the modifications to development branch.
